//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Border
    {
        public Border()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int Border_ID { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public string Border_Name { get; set; }
    
        public virtual GoodsType GoodsType { get; set; }
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
