//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsType
    {
        public GoodsType()
        {
            this.Border = new HashSet<Border>();
            this.Goods = new HashSet<Goods>();
        }
    
        public int Type_ID { get; set; }
        public string Type_Name { get; set; }
    
        public virtual ICollection<Border> Border { get; set; }
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
