//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsSave
    {
        public int GoodsSave_ID { get; set; }
        public int Goods_ID { get; set; }
        public int GoodsSave_Num { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
