//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICC
    {
        public ICC()
        {
            this.Info = new HashSet<Info>();
        }
    
        public int ICC_ID { get; set; }
        public string ICC_Name { get; set; }
        public Nullable<int> InfoClass_ID { get; set; }
    
        public virtual InfoClass InfoClass { get; set; }
        public virtual ICollection<Info> Info { get; set; }
    }
}
