//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public Info()
        {
            this.InfoComment = new HashSet<InfoComment>();
            this.InfoCommentAgainst = new HashSet<InfoCommentAgainst>();
            this.InfoCommentSupport = new HashSet<InfoCommentSupport>();
        }
    
        public int Info_ID { get; set; }
        public string Info_Title { get; set; }
        public string Info_Content { get; set; }
        public string Info_Img { get; set; }
        public System.DateTime Info_Time { get; set; }
        public int InfoClass_ID { get; set; }
        public Nullable<int> ICC_ID { get; set; }
    
        public virtual ICC ICC { get; set; }
        public virtual InfoClass InfoClass { get; set; }
        public virtual ICollection<InfoComment> InfoComment { get; set; }
        public virtual ICollection<InfoCommentAgainst> InfoCommentAgainst { get; set; }
        public virtual ICollection<InfoCommentSupport> InfoCommentSupport { get; set; }
    }
}
