//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoComment
    {
        public InfoComment()
        {
            this.InfoCommentBack = new HashSet<InfoCommentBack>();
        }
    
        public int IC_ID { get; set; }
        public int Info_ID { get; set; }
        public string IC_Content { get; set; }
        public System.DateTime IC_Time { get; set; }
        public int UserInfo_ID { get; set; }
    
        public virtual Info Info { get; set; }
        public virtual InfoComment InfoComment1 { get; set; }
        public virtual InfoComment InfoComment2 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<InfoCommentBack> InfoCommentBack { get; set; }
    }
}
