//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTEntities : DbContext
    {
        public CTEntities()
            : base("name=CTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Border> Border { get; set; }
        public DbSet<Collection> Collection { get; set; }
        public DbSet<GetGoods> GetGoods { get; set; }
        public DbSet<Goods> Goods { get; set; }
        public DbSet<GoodsComment> GoodsComment { get; set; }
        public DbSet<GoodsSave> GoodsSave { get; set; }
        public DbSet<GoodsType> GoodsType { get; set; }
        public DbSet<ICC> ICC { get; set; }
        public DbSet<Info> Info { get; set; }
        public DbSet<InfoClass> InfoClass { get; set; }
        public DbSet<InfoComment> InfoComment { get; set; }
        public DbSet<InfoCommentAgainst> InfoCommentAgainst { get; set; }
        public DbSet<InfoCommentBack> InfoCommentBack { get; set; }
        public DbSet<InfoCommentSupport> InfoCommentSupport { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<VideoClass> VideoClass { get; set; }
        public DbSet<VideoComment> VideoComment { get; set; }
        public DbSet<VideoCommentAgainst> VideoCommentAgainst { get; set; }
        public DbSet<VideoCommentBack> VideoCommentBack { get; set; }
        public DbSet<VideoCommentSupport> VideoCommentSupport { get; set; }
    }
}
