//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Collection = new HashSet<Collection>();
            this.GetGoods = new HashSet<GetGoods>();
            this.GoodsComment = new HashSet<GoodsComment>();
            this.InfoComment = new HashSet<InfoComment>();
            this.InfoCommentAgainst = new HashSet<InfoCommentAgainst>();
            this.InfoCommentBack = new HashSet<InfoCommentBack>();
            this.InfoCommentSupport = new HashSet<InfoCommentSupport>();
            this.Order = new HashSet<Order>();
            this.VideoComment = new HashSet<VideoComment>();
            this.VideoCommentAgainst = new HashSet<VideoCommentAgainst>();
            this.VideoCommentBack = new HashSet<VideoCommentBack>();
            this.VideoCommentSupport = new HashSet<VideoCommentSupport>();
        }
    
        public int UserInfo_ID { get; set; }
        public string UserInfo_Img { get; set; }
        public string UserInfo_Name { get; set; }
        public string UserInfo_Password { get; set; }
        public string UserInfo_Email { get; set; }
        public string UserInfo_Phone { get; set; }
    
        public virtual ICollection<Collection> Collection { get; set; }
        public virtual ICollection<GetGoods> GetGoods { get; set; }
        public virtual ICollection<GoodsComment> GoodsComment { get; set; }
        public virtual ICollection<InfoComment> InfoComment { get; set; }
        public virtual ICollection<InfoCommentAgainst> InfoCommentAgainst { get; set; }
        public virtual ICollection<InfoCommentBack> InfoCommentBack { get; set; }
        public virtual ICollection<InfoCommentSupport> InfoCommentSupport { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        public virtual ICollection<VideoCommentAgainst> VideoCommentAgainst { get; set; }
        public virtual ICollection<VideoCommentBack> VideoCommentBack { get; set; }
        public virtual ICollection<VideoCommentSupport> VideoCommentSupport { get; set; }
    }
}
