//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.VideoComment = new HashSet<VideoComment>();
            this.VideoCommentAgainst = new HashSet<VideoCommentAgainst>();
            this.VideoCommentSupport = new HashSet<VideoCommentSupport>();
        }
    
        public int Video_ID { get; set; }
        public string Video_Title { get; set; }
        public string Video_Url { get; set; }
        public string Video_Img { get; set; }
        public int VideoClass_ID { get; set; }
        public System.DateTime Video_Time { get; set; }
    
        public virtual VideoClass VideoClass { get; set; }
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        public virtual ICollection<VideoCommentAgainst> VideoCommentAgainst { get; set; }
        public virtual ICollection<VideoCommentSupport> VideoCommentSupport { get; set; }
    }
}
