//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoClass
    {
        public VideoClass()
        {
            this.Video = new HashSet<Video>();
        }
    
        public int VideoClass_ID { get; set; }
        public string Video_Class { get; set; }
    
        public virtual ICollection<Video> Video { get; set; }
    }
}
