//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoComment
    {
        public VideoComment()
        {
            this.VideoCommentBack = new HashSet<VideoCommentBack>();
        }
    
        public int VC_ID { get; set; }
        public int Video_ID { get; set; }
        public string VC_Content { get; set; }
        public System.DateTime VC_Time { get; set; }
        public int UserInfo_ID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Video Video { get; set; }
        public virtual ICollection<VideoCommentBack> VideoCommentBack { get; set; }
    }
}
